# This is a github action to build texty
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Texty Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run Setup
      run: |
        python -m pip install --upgrade pip
        python setup.py
    - name: Run Lint Check
      run: |
        python setup.py install
        python3 -m black --check .
    - name: Run Build
      run: |
        python setup.py build

# Path: .github/workflows/texty.yaml
# This is a github action to build typing